name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Opcional, mas ajuda a baixar dependências mais rápido
      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # Garante que as versões exigidas pelo projeto existam
      - name: Install build tools & platforms
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # Build com logs detalhados para depurar se algo falhar
      - name: Build Debug APK
        env:
          JAVA_TOOL_OPTIONS: "-Xmx2g"
        run: |
          gradle :app:assembleDebug --stacktrace --info --no-daemon

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
